services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authentication_service
    ports:
      - "8000:8000"
    environment:
      - PRODUCTION_OR_STAGING=production
      - DATABASE_URL=postgresql://user:password@db:5432/auth_db
      - SECRET_KEY=your_secret_key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: authentication_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: