services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authentication_service
    command: tail -f /dev/null
    ports:
      - "8000:8000"

  db:
    image: postgres:15
    container_name: authentication_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: