name: Lint Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - uses: ./.github/actions/setup-poetry
      
      - name: Run linting
        run: poetry run task lint
        working-directory: ./src