name: Test project authetinication and authorization service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  jobs:
    publish:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
        
      - name: Install pipx
        run: apt install -y pipx

      - name: Install poetry
        run: pipx install poetry==2.2.1

      - name: Add Poetry to PATH
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH