name: Test project authentication and authorization service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-poetry
      
      - name: Run tests
        run: poetry run task test
        working-directory: ./src